/*
 * The MIT License
 *
 * Copyright 2015-2016 Wes Hampson <thehambone93@gmail.com>.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

package thehambone.blackopsterminalemulator.filesystem.command;

import java.util.HashMap;
import java.util.Map;
import thehambone.blackopsterminalemulator.Terminal;
import thehambone.blackopsterminalemulator.filesystem.ExecutableFile;

/**
 * The "encode" command.
 * <p>
 * Encodes a string.
 * <p>
 * Created on Dec 6, 2015.
 *
 * @author Wes Hampson
 */
public class EncodeCommand extends ExecutableFile
{
    // TODO: find a way to encode mathematically
    private static final Map<String, String> CIPHER_TABLE = new HashMap<>();
    static
    {
        CIPHER_TABLE.put("A", "IM");
        CIPHER_TABLE.put("B", "DKM");
        CIPHER_TABLE.put("C", "DJM");
        CIPHER_TABLE.put("D", "DG");
        CIPHER_TABLE.put("E", "G");
        CIPHER_TABLE.put("F", "EJM");
        CIPHER_TABLE.put("G", "FG");
        CIPHER_TABLE.put("H", "EKM");
        CIPHER_TABLE.put("I", "KM");
        CIPHER_TABLE.put("J", "CLM");
        CIPHER_TABLE.put("K", "DH");
        CIPHER_TABLE.put("L", "CAG");
        CIPHER_TABLE.put("M", "LM");
        CIPHER_TABLE.put("N", "JM");
        CIPHER_TABLE.put("O", "FH");
        CIPHER_TABLE.put("P", "CJM");
        CIPHER_TABLE.put("Q", "FIM");
        CIPHER_TABLE.put("R", "CG");
        CIPHER_TABLE.put("S", "EG");
        CIPHER_TABLE.put("T", "H");
        CIPHER_TABLE.put("U", "EH");
        CIPHER_TABLE.put("V", "EIM");
        CIPHER_TABLE.put("W", "CH");
        CIPHER_TABLE.put("X", "DIM");
        CIPHER_TABLE.put("Y", "DLM");
        CIPHER_TABLE.put("Z", "FKM");
        CIPHER_TABLE.put("0", "FFH");
        CIPHER_TABLE.put("1", "CFH");
        CIPHER_TABLE.put("2", "EFH");
        CIPHER_TABLE.put("3", "ECH");
        CIPHER_TABLE.put("4", "EEH");
        CIPHER_TABLE.put("5", "EEG");
        CIPHER_TABLE.put("6", "DEG");
        CIPHER_TABLE.put("7", "FEG");
        CIPHER_TABLE.put("8", "FDG");
        CIPHER_TABLE.put("9", "FFG");
    }
    
    /**
     * Creates a new instance of the {@code EncodeCommand} class.
     * 
     * @param id the filesystem object id
     */
    public EncodeCommand(int id)
    {
        super(id, "encode");
    }
    
    /*
     * Creates a random permutation of the encoded letter.
     * Permutations can be generated by increasing any letter in the encoded
     * string by 13 letters if it comes before the letter O. For instance, a
     * permutation of IM could be VZ, because I + 13 = V and M + 13 = Z.
     */
    private String permutate(String encodedLetter)
    {
        String permutation = "";
        char c;
        
        // Iterate over all letters
        for (int i = 0; i < encodedLetter.length(); i++) {
            c = encodedLetter.charAt(i);
            
            // Randomly choose whether to add 13 to the letter
            if (Math.round(Math.random()) == 1) {
                permutation += (char)(c + 13);
            } else {
                permutation += c;
            }
        }
        
        return permutation;
    }
    
    @Override
    public void exec(String[] args)
    {
        // Combine all arguments into a single string separated by spaces
        String encodeStr = "";
        for (String arg : args) {
            encodeStr += arg + " ";
        }
        encodeStr = encodeStr.toUpperCase().trim();
        
        String result = "";
        String encodedLetter;
        char c;
        
        // Encode string letter by letter
        for (int i = 0; i < encodeStr.length(); i++) {
            c = encodeStr.charAt(i);
            encodedLetter = CIPHER_TABLE.get(Character.toString(c));
            if (encodedLetter == null) {
                encodedLetter = "M";
            }
            result += permutate(encodedLetter);
            
        }

        Terminal.println(result);
    }
}
